
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const BulkInvoiceProcessor = lazy(() => import("./pages/BulkInvoiceProcessor.tsx"));
const ContactUs = lazy(() => import("./pages/ContactUs.tsx"));
const ContractComparison = lazy(() => import("./pages/ContractComparison.tsx"));
const DashboardSummary = lazy(() => import("./pages/DashboardSummary.tsx"));
const HistoryViewer = lazy(() => import("./pages/HistoryViewer.tsx"));
const InvoiceAudit = lazy(() => import("./pages/InvoiceAudit.tsx"));
const InvoiceDashboard = lazy(() => import("./pages/InvoiceDashboard.tsx"));
const PrivacyPolicy = lazy(() => import("./pages/PrivacyPolicy.tsx"));
const RedFlagVisualizer = lazy(() => import("./pages/RedFlagVisualizer.tsx"));
const TermsOfService = lazy(() => import("./pages/TermsOfService.tsx"));
const UploadPage = lazy(() => import("./pages/UploadPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/bulk-invoice-processor", element: <BulkInvoiceProcessor />},
	{ path: "/bulkinvoiceprocessor", element: <BulkInvoiceProcessor />},
	{ path: "/contact-us", element: <ContactUs />},
	{ path: "/contactus", element: <ContactUs />},
	{ path: "/contract-comparison", element: <ContractComparison />},
	{ path: "/contractcomparison", element: <ContractComparison />},
	{ path: "/dashboard-summary", element: <DashboardSummary />},
	{ path: "/dashboardsummary", element: <DashboardSummary />},
	{ path: "/history-viewer", element: <HistoryViewer />},
	{ path: "/historyviewer", element: <HistoryViewer />},
	{ path: "/invoice-audit", element: <InvoiceAudit />},
	{ path: "/invoiceaudit", element: <InvoiceAudit />},
	{ path: "/invoice-dashboard", element: <InvoiceDashboard />},
	{ path: "/invoicedashboard", element: <InvoiceDashboard />},
	{ path: "/privacy-policy", element: <PrivacyPolicy />},
	{ path: "/privacypolicy", element: <PrivacyPolicy />},
	{ path: "/red-flag-visualizer", element: <RedFlagVisualizer />},
	{ path: "/redflagvisualizer", element: <RedFlagVisualizer />},
	{ path: "/terms-of-service", element: <TermsOfService />},
	{ path: "/termsofservice", element: <TermsOfService />},
	{ path: "/upload-page", element: <UploadPage />},
	{ path: "/uploadpage", element: <UploadPage />},

];
